-- 007_assessment_questions_seed.sql
-- Seed file for Assessment Engine questions (SIH 2026, PS 26044)
-- Contains high-quality, industry-realistic questions across 5 disciplines.

-- CSE & AI-DS: Baseline
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('CSE & AI-DS', '{}', 'Data Structures', 'technical', 'Which data structure is most appropriate for implementing a least recently used (LRU) cache?', '[{"id": "a", "text": "Hash Map", "is_correct": false}, {"id": "b", "text": "Hash Map and Doubly Linked List", "is_correct": true}, {"id": "c", "text": "Binary Search Tree", "is_correct": false}, {"id": "d", "text": "Array and Singly Linked List", "is_correct": false}]', 3, 'multiple_choice', 'An LRU cache requires O(1) time complexity for both access and eviction. A Hash Map provides O(1) access, while a Doubly Linked List allows O(1) removals and additions at the ends.'),
('CSE & AI-DS', '{}', 'Algorithms', 'technical', 'In a microservices architecture, which algorithm is commonly used for distributed rate limiting?', '[{"id": "a", "text": "Dijkstras Algorithm", "is_correct": false}, {"id": "b", "text": "Token Bucket", "is_correct": true}, {"id": "c", "text": "Binary Search", "is_correct": false}, {"id": "d", "text": "K-Means Clustering", "is_correct": false}]', 4, 'multiple_choice', 'The Token Bucket algorithm allows for controlling the rate of incoming requests by managing a bucket of tokens, where each request consumes a token.');

-- CSE & AI-DS: Role-Specific (Software Engineer - assuming mock UUID '11111111-1111-1111-1111-111111111111')
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('CSE & AI-DS', '{"11111111-1111-1111-1111-111111111111"}', 'System Design', 'technical', 'You are designing a high-throughput chat application. What is the most efficient way to push real-time messages from the server to the client?', '[{"id": "a", "text": "HTTP Short Polling", "is_correct": false}, {"id": "b", "text": "WebSockets", "is_correct": true}, {"id": "c", "text": "REST API GET requests", "is_correct": false}, {"id": "d", "text": "GraphQL Mutations", "is_correct": false}]', 3, 'scenario_based', 'WebSockets provide a persistent, full-duplex communication channel over a single TCP connection, ideal for real-time low-latency applications like chat.'),
('CSE & AI-DS', '{"11111111-1111-1111-1111-111111111111"}', 'Database Optimization', 'technical', 'A SQL query is performing a full table scan on a large table despite having an index on the column in the WHERE clause (e.g., `WHERE LOWER(email) = "test@example.com"`). What is the most likely reason?', '[{"id": "a", "text": "The index is corrupt", "is_correct": false}, {"id": "b", "text": "Using a function on the indexed column prevents index usage", "is_correct": true}, {"id": "c", "text": "The table is locked", "is_correct": false}, {"id": "d", "text": "The index needs to be rebuilt", "is_correct": false}]', 4, 'scenario_based', 'Applying a function like LOWER() to a column in a WHERE clause makes the query unsargable, forcing the database to evaluate the function for every row and bypassing standard B-Tree indexes unless a functional index is used.');

-- ECE/VLSI: Baseline
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('ECE/VLSI', '{}', 'Digital Logic', 'technical', 'What is the primary advantage of using synchronous sequential circuits over asynchronous ones in FPGA design?', '[{"id": "a", "text": "Lower power consumption", "is_correct": false}, {"id": "b", "text": "Immunity to race conditions and predictable timing", "is_correct": true}, {"id": "c", "text": "Fewer logic gates required", "is_correct": false}, {"id": "d", "text": "Faster propagation delays", "is_correct": false}]', 2, 'multiple_choice', 'Synchronous circuits use a global clock signal, which eliminates race conditions and hazards that plague asynchronous designs, making timing analysis and verification much more straightforward.');

-- ECE/VLSI: Role-Specific (Hardware Verification Engineer)
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('ECE/VLSI', '{"22222222-2222-2222-2222-222222222222"}', 'UVM Verification', 'technical', 'In the Universal Verification Methodology (UVM), what is the primary purpose of a scoreboard?', '[{"id": "a", "text": "To drive stimulus to the DUT", "is_correct": false}, {"id": "b", "text": "To compare the expected output against the actual DUT output", "is_correct": true}, {"id": "c", "text": "To generate clock and reset signals", "is_correct": false}, {"id": "d", "text": "To collect coverage metrics", "is_correct": false}]', 4, 'multiple_choice', 'The UVM scoreboard receives transactions from the monitor and compares the actual Device Under Test (DUT) output with expected results generated by a reference model.');

-- Mechanical: Baseline
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('Mechanical', '{}', 'Thermodynamics', 'technical', 'In an ideal vapor-compression refrigeration cycle, what is the state of the refrigerant immediately exiting the expansion valve?', '[{"id": "a", "text": "Superheated vapor", "is_correct": false}, {"id": "b", "text": "Subcooled liquid", "is_correct": false}, {"id": "c", "text": "Liquid-vapor mixture", "is_correct": true}, {"id": "d", "text": "Saturated vapor", "is_correct": false}]', 3, 'multiple_choice', 'The expansion valve throttles the high-pressure liquid, causing a sudden drop in pressure. This causes some liquid to flash into vapor, resulting in a low-pressure liquid-vapor mixture entering the evaporator.');

-- Mechanical: Role-Specific (Design Engineer)
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('Mechanical', '{"33333333-3333-3333-3333-333333333333"}', 'CAD/FEA', 'technical', 'When setting up a Finite Element Analysis (FEA) for a thin-walled pressure vessel, which element type provides the most computationally efficient and accurate results?', '[{"id": "a", "text": "3D Solid elements (Tetrahedrons)", "is_correct": false}, {"id": "b", "text": "2D Shell elements", "is_correct": true}, {"id": "c", "text": "1D Beam elements", "is_correct": false}, {"id": "d", "text": "Rigid body elements", "is_correct": false}]', 4, 'scenario_based', 'For thin-walled structures, 2D shell elements capture bending and membrane stresses accurately while requiring significantly fewer degrees of freedom compared to 3D solid elements.');

-- Civil: Baseline
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('Civil', '{}', 'Structural Analysis', 'technical', 'For a simply supported beam subject to a uniformly distributed load, where does the maximum bending moment occur?', '[{"id": "a", "text": "At the supports", "is_correct": false}, {"id": "b", "text": "At the mid-span", "is_correct": true}, {"id": "c", "text": "At quarter-span", "is_correct": false}, {"id": "d", "text": "It is constant throughout", "is_correct": false}]', 2, 'multiple_choice', 'For a simply supported beam with a UDL (w) and length (L), the bending moment equation is parabolic, peaking at the mid-span with a value of wL^2/8.');

-- Civil: Role-Specific (Geotechnical Engineer)
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('Civil', '{"44444444-4444-4444-4444-444444444444"}', 'Soil Mechanics', 'technical', 'During a triaxial shear test on normally consolidated clay, what is the expected result under un-drained conditions?', '[{"id": "a", "text": "Volume decreases continuously", "is_correct": false}, {"id": "b", "text": "Excess pore water pressure is zero", "is_correct": false}, {"id": "c", "text": "Excess positive pore water pressure develops", "is_correct": true}, {"id": "d", "text": "Negative pore water pressure develops", "is_correct": false}]', 5, 'scenario_based', 'In an un-drained test, water cannot escape. For normally consolidated clay (which tends to contract upon shearing), this tendency causes a buildup of positive excess pore water pressure, reducing effective stress.');

-- Electrical: Baseline
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('Electrical', '{}', 'Power Systems', 'technical', 'What is the primary function of a tap changer in a power transformer?', '[{"id": "a", "text": "To change the frequency of the output voltage", "is_correct": false}, {"id": "b", "text": "To regulate the output voltage by altering the turns ratio", "is_correct": true}, {"id": "c", "text": "To convert AC to DC", "is_correct": false}, {"id": "d", "text": "To act as a protective relay", "is_correct": false}]', 2, 'multiple_choice', 'A tap changer regulates the output voltage by selecting a variable tap point along the transformer winding, effectively changing the turns ratio between the primary and secondary coils.');

-- Electrical: Role-Specific (Power Electronics Engineer)
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('Electrical', '{"55555555-5555-5555-5555-555555555555"}', 'Inverter Design', 'technical', 'In a three-phase Voltage Source Inverter (VSI), what is the main advantage of using Space Vector Pulse Width Modulation (SVPWM) over Sinusoidal PWM (SPWM)?', '[{"id": "a", "text": "SVPWM requires fewer switches", "is_correct": false}, {"id": "b", "text": "SVPWM is completely immune to harmonic distortion", "is_correct": false}, {"id": "c", "text": "SVPWM provides a higher fundamental output voltage (up to 15% more)", "is_correct": true}, {"id": "d", "text": "SVPWM operates without a DC link capacitor", "is_correct": false}]', 5, 'multiple_choice', 'SVPWM utilizes the DC bus voltage more efficiently than conventional SPWM, generating a maximum fundamental line voltage that is about 15.4% higher before entering the over-modulation region.');

-- Soft Skills / SJT (Cross-Discipline)
INSERT INTO assessment_questions (discipline, target_role_ids, skill_tag, skill_category, question_text, options, difficulty_level, question_type, explanation) VALUES
('CSE & AI-DS', '{}', 'Teamwork', 'soft_skills', 'You are working on a tight deadline, and a team member is repeatedly failing to deliver their portion of the code, blocking your progress. What is the most effective action to take?', '[{"id": "a", "text": "Write the code for them to ensure the deadline is met.", "is_correct": false}, {"id": "b", "text": "Complain to the project manager immediately to protect yourself.", "is_correct": false}, {"id": "c", "text": "Have a private, constructive conversation with the team member to understand their blockers and offer help if feasible.", "is_correct": true}, {"id": "d", "text": "Ignore it and wait; it is their responsibility.", "is_correct": false}]', 3, 'scenario_based', 'Addressing the issue directly and constructively with the individual fosters teamwork and problem-solving, rather than escalating prematurely or taking over their work.'),
('Mechanical', '{}', 'Ethics', 'soft_skills', 'During testing of a new mechanical component, you notice a minor safety flaw that occurs only in extreme, unlikely conditions. The product manager wants to ship it as-is to meet the launch date. What should you do?', '[{"id": "a", "text": "Agree with the PM, as the conditions are unlikely.", "is_correct": false}, {"id": "b", "text": "Document the flaw comprehensively, formally express your safety concerns, and escalate if necessary.", "is_correct": true}, {"id": "c", "text": "Leak the information to the press to halt production.", "is_correct": false}, {"id": "d", "text": "Secretly try to fix it before shipping without telling anyone.", "is_correct": false}]', 4, 'scenario_based', 'Engineering ethics dictate that public safety is paramount. You must formally document the risk and escalate through proper channels if safety is compromised, even for unlikely edge cases.');
