import { LearningResource } from '@/types';

export const MOCK_LEARNING_RESOURCES: LearningResource[] = [
  // ─── 1. Electronics & VLSI ───
  {
    id: 'lr-1',
    title: 'NPTEL VLSI Design (IIT Kharagpur) — SystemVerilog & RTL Synthesis',
    provider: 'NPTEL / IIT Kharagpur',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Intermediate',
    skillAddressed: 'Verilog / VHDL',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.8,
    enrollUrl: 'https://nptel.ac.in/courses/117105080',
    image: 'https://images.unsplash.com/photo-1580983218765-f663bec07b37?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-2',
    title: 'Texas Instruments Precision ADC & Signal Chain Design Track',
    provider: 'Texas Instruments Precision Labs',
    type: 'Course',
    duration: '6 Weeks (Self-paced)',
    level: 'Advanced',
    skillAddressed: 'Circuit Analysis & SPICE',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.9,
    enrollUrl: 'https://ti.com/precision-labs',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Texas Instruments'
  },
  {
    id: 'lr-2b',
    title: 'ARM University: Embedded Firmware & Bare-Metal C Programming',
    provider: 'ARM Education Program',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Intermediate',
    skillAddressed: 'Embedded C',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.9,
    enrollUrl: 'https://arm.com/resources/education',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'ARM Ltd.'
  },
  {
    id: 'lr-2c',
    title: 'FreeRTOS Real-Time Kernel for ARM Cortex-M Microcontrollers',
    provider: 'AWS / FreeRTOS Academy',
    type: 'Course',
    duration: '6 Weeks (Self-paced)',
    level: 'Advanced',
    skillAddressed: 'FreeRTOS',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.8,
    enrollUrl: 'https://freertos.org',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Amazon FreeRTOS'
  },
  {
    id: 'lr-2d',
    title: 'ARM Cortex-M Architecture, Exception Handling & Peripheral Interfacing',
    provider: 'STMicroelectronics / NPTEL',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Intermediate',
    skillAddressed: 'ARM Cortex-M',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.7,
    enrollUrl: 'https://st.com/mcu-education',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-2e',
    title: 'Xilinx Vivado: FPGA Digital Design & Static Timing Analysis Closure',
    provider: 'AMD Xilinx University Program',
    type: 'Certification',
    duration: '6 Weeks',
    level: 'Advanced',
    skillAddressed: 'FPGA Prototyping',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.9,
    enrollUrl: 'https://xilinx.com/university',
    image: 'https://images.unsplash.com/photo-1580983218765-f663bec07b37?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'AMD Xilinx'
  },
  {
    id: 'lr-2f',
    title: 'Cadence Virtuoso: Custom IC Layout, DRC/LVS & Mixed-Signal Simulation',
    provider: 'Cadence Academic Network',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Advanced',
    skillAddressed: 'Cadence Virtuoso',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.8,
    enrollUrl: 'https://cadence.com/learn',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Cadence Design Systems'
  },
  {
    id: 'lr-2g',
    title: 'Altium Academy: High-Speed 4-Layer PCB Design & Signal Integrity',
    provider: 'Altium Education',
    type: 'Course',
    duration: '4 Weeks (Self-paced)',
    level: 'Intermediate',
    skillAddressed: 'Altium PCB Design',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    rating: 4.8,
    enrollUrl: 'https://altium.com/education',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Altium'
  },

  // ─── 2. Mechanical, Robotics & EV ───
  {
    id: 'lr-3',
    title: 'Ansys Innovation: Structural FEA & Modal Vibration Simulation',
    provider: 'Ansys Innovation Courses',
    type: 'Certification',
    duration: '8 Weeks (Self-paced)',
    level: 'Intermediate',
    skillAddressed: 'Ansys FEA / CFD',
    engineeringCluster: 'Mechanical, Robotics & Automotive EV',
    rating: 4.9,
    enrollUrl: 'https://innovationspace.ansys.com',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Ansys Inc.'
  },
  {
    id: 'lr-4',
    title: 'NPTEL Robotics & Control: Kinematics, Dynamics & ROS 2 (IIT Kharagpur)',
    provider: 'NPTEL / IIT Kharagpur',
    type: 'Certification',
    duration: '12 Weeks',
    level: 'Intermediate',
    skillAddressed: 'ROS 2 / Navigation',
    engineeringCluster: 'Mechanical, Robotics & Automotive EV',
    rating: 4.8,
    enrollUrl: 'https://nptel.ac.in',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-4b',
    title: 'Dassault Systèmes Certified SolidWorks Professional (CSWP) Training',
    provider: 'Dassault Systèmes',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Intermediate',
    skillAddressed: 'SolidWorks CAD',
    engineeringCluster: 'Mechanical, Robotics & Automotive EV',
    rating: 4.9,
    enrollUrl: 'https://solidworks.com/certification',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Dassault Systèmes'
  },
  {
    id: 'lr-4c',
    title: 'ASME Y14.5 Geometric Dimensioning & Tolerancing (GD&T) in Design',
    provider: 'ASME Training & NPTEL',
    type: 'Course',
    duration: '6 Weeks',
    level: 'Intermediate',
    skillAddressed: 'GD&T Tolerancing',
    engineeringCluster: 'Mechanical, Robotics & Automotive EV',
    rating: 4.8,
    enrollUrl: 'https://asme.org/gdt',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },

  // ─── 3. Civil & Smart Infrastructure ───
  {
    id: 'lr-5',
    title: 'Bentley Institute: STAAD.Pro Structural Steel & Concrete Analysis',
    provider: 'Bentley Institute',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Intermediate',
    skillAddressed: 'Structural Analysis (STAAD.Pro)',
    engineeringCluster: 'Civil & Smart Infrastructure',
    rating: 4.8,
    enrollUrl: 'https://bentley.com/learn',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Bentley Systems'
  },
  {
    id: 'lr-6',
    title: 'NPTEL Advanced Concrete Technology & IS 456 Limit State Design (IIT Roorkee)',
    provider: 'NPTEL / IIT Roorkee',
    type: 'Certification',
    duration: '12 Weeks',
    level: 'Intermediate',
    skillAddressed: 'Reinforced Concrete (IS 456)',
    engineeringCluster: 'Civil & Smart Infrastructure',
    rating: 4.9,
    enrollUrl: 'https://nptel.ac.in',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-6b',
    title: 'Autodesk Certified: Revit Structure 3D BIM & Parametric Detailing',
    provider: 'Autodesk Learning Academy',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Intermediate',
    skillAddressed: 'Revit BIM Modeling',
    engineeringCluster: 'Civil & Smart Infrastructure',
    rating: 4.8,
    enrollUrl: 'https://autodesk.com/certification',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Autodesk'
  },
  {
    id: 'lr-6c',
    title: 'AutoCAD Civil 3D Highway Corridor Design & Earthwork Calculations',
    provider: 'NPTEL / IIT Delhi',
    type: 'Course',
    duration: '6 Weeks',
    level: 'Intermediate',
    skillAddressed: 'AutoCAD Civil 3D',
    engineeringCluster: 'Civil & Smart Infrastructure',
    rating: 4.7,
    enrollUrl: 'https://nptel.ac.in',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },

  // ─── 4. Electrical & Power Systems ───
  {
    id: 'lr-7',
    title: 'MathWorks: MATLAB & Simulink Electric Vehicle Powertrain Onramp',
    provider: 'MathWorks Training',
    type: 'Certification',
    duration: '6 Weeks (Self-paced)',
    level: 'Intermediate',
    skillAddressed: 'Power Electronics',
    engineeringCluster: 'Electrical, Power Systems & Renewable Energy',
    rating: 4.9,
    enrollUrl: 'https://matlabacademy.mathworks.com',
    image: 'https://images.unsplash.com/photo-1558441719-8b489c634a10?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'MathWorks'
  },
  {
    id: 'lr-8',
    title: 'NPTEL Industrial Automation, PLC & SCADA Systems (IIT Delhi)',
    provider: 'NPTEL / IIT Delhi',
    type: 'Certification',
    duration: '8 Weeks',
    level: 'Intermediate',
    skillAddressed: 'PLC & SCADA Automation',
    engineeringCluster: 'Electrical, Power Systems & Renewable Energy',
    rating: 4.7,
    enrollUrl: 'https://nptel.ac.in',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-8b',
    title: 'Automotive Battery Management Systems (BMS) Architecture & SOC Estimation',
    provider: 'NPTEL / IIT Madras',
    type: 'Certification',
    duration: '10 Weeks',
    level: 'Advanced',
    skillAddressed: 'Battery Management (BMS)',
    engineeringCluster: 'Electrical, Power Systems & Renewable Energy',
    rating: 4.9,
    enrollUrl: 'https://nptel.ac.in',
    image: 'https://images.unsplash.com/photo-1558441719-8b489c634a10?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-8c',
    title: 'Field-Oriented Control (FOC) & Space Vector Modulation for PMSM Motors',
    provider: 'Texas Instruments / MathWorks',
    type: 'Course',
    duration: '6 Weeks',
    level: 'Advanced',
    skillAddressed: 'Motor Drives & FOC',
    engineeringCluster: 'Electrical, Power Systems & Renewable Energy',
    rating: 4.8,
    enrollUrl: 'https://ti.com/c2000-motor',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Texas Instruments'
  },

  // ─── 5. Computer Science & AI / IT ───
  {
    id: 'lr-9',
    title: 'NPTEL Deep Learning (IIT Madras) — 12-Week AICTE Track',
    provider: 'NPTEL / IIT Madras',
    type: 'Certification',
    duration: '12 Weeks (Self-paced)',
    level: 'Intermediate',
    skillAddressed: 'TensorFlow / PyTorch',
    engineeringCluster: 'Computer Science & Information Technology',
    rating: 4.9,
    enrollUrl: 'https://nptel.ac.in/courses/106106213',
    image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-10',
    title: 'MIT 6.824: Distributed Systems & Raft Consensus Architecture',
    provider: 'MIT OpenCourseWare',
    type: 'Course',
    duration: '8 Weeks (Self-paced)',
    level: 'Advanced',
    skillAddressed: 'Distributed Systems',
    engineeringCluster: 'Computer Science & Information Technology',
    rating: 4.9,
    enrollUrl: 'https://pdos.csail.mit.edu/6.824/',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=400',
    isFree: true
  },
  {
    id: 'lr-11',
    title: 'AWS Academy Cloud Architecting: Scalable Systems & EC2/S3 Microservices',
    provider: 'Amazon Web Services (AWS)',
    type: 'Certification',
    duration: '6 Weeks (Self-paced)',
    level: 'Intermediate',
    skillAddressed: 'Cloud Computing (AWS)',
    engineeringCluster: 'Computer Science & Information Technology',
    rating: 4.9,
    enrollUrl: 'https://aws.amazon.com/training',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Amazon Web Services'
  },
  {
    id: 'lr-12',
    title: 'Google Cloud Production ML Systems & Vertex AI Deployment',
    provider: 'Google Cloud Training',
    type: 'Workshop',
    duration: '4 Weeks',
    level: 'Advanced',
    skillAddressed: 'Machine Learning',
    engineeringCluster: 'Computer Science & Information Technology',
    rating: 4.8,
    enrollUrl: 'https://cloud.google.com/training',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400',
    isFree: true,
    publishedByIndustry: 'Google'
  }
];
