import { Opportunity } from '@/types';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  // ─── 1. Electronics & VLSI ───
  {
    id: 'opp-1',
    title: 'VLSI Design Intern — Modem IP Group',
    company: 'Qualcomm India Pvt. Ltd.',
    companyLogo: '📡',
    location: 'Hyderabad, Telangana (Onsite)',
    type: 'Internship',
    stipend: '₹60,000 / month',
    duration: '6 Months',
    deadline: '2026-10-10',
    domain: 'VLSI / Semiconductor',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    cadToolsRequired: ['Xilinx Vivado', 'Cadence Innovus', 'Synopsys VCS'],
    industryStandards: ['AXI4 Protocol', 'IEEE 1800 SystemVerilog', 'UVM 1.2'],
    requiredSkills: ['Verilog / VHDL', 'FPGA Prototyping', 'C++', 'Git & Linux', 'Signal Processing (DSP)'],
    minimumCGPA: 8.2,
    eligibleBranches: ['Electrical Engineering (VLSI Specialisation)', 'Electronics & Communication Engineering', 'Microelectronics'],
    description: 'Contribute to RTL design and verification of next-generation 5G NR modem IP blocks within Qualcomm\'s Hyderabad Modem Group.',
    responsibilities: [
      'Write synthesisable RTL in SystemVerilog for baseband DSP modules.',
      'Develop UVM testbenches and functional coverage models.',
      'Perform static timing analysis (STA) closure and logic equivalence checks.',
      'Participate in design review with Senior VLSI Principal Engineers.'
    ],
    perks: ['Pre-Placement Offer (PPO) track', 'Qualcomm VLSI Certification', 'Health Insurance coverage during internship']
  },
  {
    id: 'opp-2',
    title: 'Analog & Mixed-Signal IC Intern — Precision ADC Group',
    company: 'Texas Instruments India',
    companyLogo: '⚡',
    location: 'Bengaluru, Karnataka (Onsite)',
    type: 'Internship',
    stipend: '₹65,000 / month',
    duration: '6 Months',
    deadline: '2026-10-25',
    domain: 'Analog & Mixed-Signal Electronics',
    engineeringCluster: 'Electronics & Communication (VLSI & Embedded)',
    cadToolsRequired: ['Cadence Virtuoso', 'SPICE', 'Altium Designer'],
    industryStandards: ['JEDEC', 'IPC-2221', 'AEC-Q100'],
    requiredSkills: ['Circuit Analysis & SPICE', 'Altium PCB Design', 'Embedded C', 'MATLAB / Simulink', 'Signal Processing (DSP)'],
    minimumCGPA: 8.0,
    eligibleBranches: ['Electronics & Communication Engineering', 'Electrical Engineering', 'Instrumentation'],
    description: 'Design and simulate high-speed delta-sigma analog-to-digital converters and precision op-amp circuits using Cadence Virtuoso.',
    responsibilities: [
      'Simulate analog front-end circuits across PVT corners.',
      'Perform silicon validation in TI high-precision characterization lab.',
      'Design test PCB fixtures using Altium Designer.',
      'Document silicon errata and technical application notes.'
    ],
    perks: ['PPO track for Analog Design Engineer', 'TI precision lab badge', 'Mentor assigned from TI Fellow network']
  },

  // ─── 2. Mechanical, Robotics & Automotive / EV ───
  {
    id: 'opp-3',
    title: 'EV Battery Pack Thermal & Structural Design Intern',
    company: 'Ather Energy',
    companyLogo: '🔋',
    location: 'Bengaluru / Hosur Plant (Hybrid)',
    type: 'Internship',
    stipend: '₹45,000 / month',
    duration: '6 Months',
    deadline: '2026-10-18',
    domain: 'EV Engineering & Thermal Systems',
    engineeringCluster: 'Mechanical, Robotics & Automotive EV',
    cadToolsRequired: ['SolidWorks', 'Ansys Fluent (CFD)', 'Ansys Mechanical (FEA)'],
    industryStandards: ['AIS-156 Amendment 3', 'ISO 26262', 'ASME Y14.5 (GD&T)'],
    requiredSkills: ['SolidWorks CAD', 'Ansys FEA / CFD', 'Thermodynamics & Heat Transfer', 'GD&T', 'Materials Science'],
    minimumCGPA: 7.8,
    eligibleBranches: ['Mechanical Engineering', 'Mechatronics', 'Automobile Engineering', 'Aerospace Engineering'],
    description: 'Design robust aluminum die-cast battery enclosures and computational thermal management channels for 450X electric scooter battery packs.',
    responsibilities: [
      'Conduct conjugate heat transfer (CHT) CFD simulations for liquid and air cooling in Ansys Fluent.',
      'Execute structural drop test and modal vibration FEA according to AIS-156 safety standards.',
      'Create production 2D manufacturing drawings with strict GD&T tolerances in SolidWorks.',
      'Perform thermal chamber validation on prototype battery modules.'
    ],
    perks: ['PPO review after 4 months', 'Free Ather scooter commute lease during internship', 'Hands-on access to R&D rapid prototyping shop']
  },
  {
    id: 'opp-4',
    title: 'Autonomous Mobile Robot (AMR) Navigation Engineer',
    company: 'GreyOrange Robotics',
    companyLogo: '🤖',
    location: 'Gurugram, NCR (Onsite)',
    type: 'Internship',
    stipend: '₹50,000 / month',
    duration: '6 Months',
    deadline: '2026-10-30',
    domain: 'Robotics & Autonomous Systems',
    engineeringCluster: 'Mechanical, Robotics & Automotive EV',
    cadToolsRequired: ['Gazebo Simulator', 'ROS 2 Humble', 'RViz', 'SolidWorks'],
    industryStandards: ['ROS 2 Industrial', 'ISO 3691-4 (Industrial AMR Safety)'],
    requiredSkills: ['ROS 2 / Navigation', 'C++', 'Python', 'Kinematics & Dynamics', 'Git & Linux'],
    minimumCGPA: 8.0,
    eligibleBranches: ['Mechanical Engineering', 'Mechatronics', 'Computer Science and Engineering', 'Robotics & Automation'],
    description: 'Work on cutting-edge warehouse Butler AMRs. Implement SLAM localization and dynamic obstacle avoidance algorithms running in ROS 2.',
    responsibilities: [
      'Develop dynamic path planning plugins in ROS 2 Nav2 stack.',
      'Simulate warehouse fleet scenarios in Gazebo physics engine.',
      'Integrate 2D LiDAR, 3D depth cameras, and wheel odometry with EKF sensor fusion.',
      'Deploy firmware updates to physical AMR test fleet.'
    ],
    perks: ['PPO track with ₹14 LPA base package', 'GreyOrange Innovation Labs pass', 'Direct mentorship from Robotics Director']
  },
  {
    id: 'opp-5',
    title: 'Chassis & Crashworthiness Simulation Trainee',
    company: 'Tata Motors Engineering Research Centre (ERC)',
    companyLogo: '🚗',
    location: 'Pune, Maharashtra (Onsite)',
    type: 'Full-time',
    stipend: '₹8.0 LPA',
    duration: 'Full-time Role',
    deadline: '2026-11-10',
    domain: 'Automotive CAE & Crash Simulation',
    engineeringCluster: 'Mechanical, Robotics & Automotive EV',
    cadToolsRequired: ['HyperMesh', 'LS-DYNA', 'CATIA V5'],
    industryStandards: ['Bharat NCAP 5-Star', 'ECE R94', 'AIS-098'],
    requiredSkills: ['Ansys FEA / CFD', 'SolidWorks CAD', 'Kinematics & Dynamics', 'Materials Science', 'GD&T'],
    minimumCGPA: 7.5,
    eligibleBranches: ['Mechanical Engineering', 'Automobile Engineering', 'Production Engineering'],
    description: 'Join Tata Motors ERC. Model non-linear frontal and side crash simulations targeting Bharat NCAP 5-star safety ratings for future EV platforms.',
    responsibilities: [
      'Build finite element meshes of BIW (Body in White) components in Altair HyperMesh.',
      'Set up non-linear explicit dynamic crash simulations in LS-DYNA.',
      'Analyze energy absorption zones, crumple dynamics, and cabin intrusion.',
      'Coordinate with structural testing team for physical sled test correlation.'
    ],
    perks: ['Graduate Engineer Trainee (GET) onboarding', 'Tata ERC automotive certification', 'Tata Motors vehicle purchase discount']
  },

  // ─── 3. Civil, Structural & Smart Infrastructure ───
  {
    id: 'opp-6',
    title: 'Graduate Structural Engineer Trainee — Metro & Bridges',
    company: 'Larsen & Toubro Construction (ECC Division)',
    companyLogo: '🏗️',
    location: 'Chennai / Delhi NCR Metro Projects (Onsite)',
    type: 'Full-time',
    stipend: '₹7.5 LPA',
    duration: 'Full-time Role',
    deadline: '2026-11-20',
    domain: 'Structural Engineering & Metro Infrastructure',
    engineeringCluster: 'Civil & Smart Infrastructure',
    cadToolsRequired: ['STAAD.Pro', 'AutoCAD Civil 3D', 'ETABS'],
    industryStandards: ['IS 456:2000', 'IS 1893 (Earthquake)', 'IRC 112 (Bridges)'],
    requiredSkills: ['Structural Analysis (STAAD.Pro)', 'Reinforced Concrete (IS 456)', 'AutoCAD Civil 3D', 'Geotechnical Engineering', 'Surveying & GIS'],
    minimumCGPA: 7.5,
    eligibleBranches: ['Civil Engineering', 'Structural Engineering', 'Infrastructure Engineering'],
    description: 'Design pre-stressed concrete viaducts, underground metro station boxes, and elevated pier foundations for urban mass transit systems.',
    responsibilities: [
      'Perform 3D structural frame and seismic analysis using Bentley STAAD.Pro and ETABS.',
      'Calculate bending moment envelopes, shear reinforcement, and deflection limits per IS 456.',
      'Review soil strata geotechnical borehole data and size deep bored pile foundations.',
      'Prepare Bar Bending Schedules (BBS) and structural detailing drawings in AutoCAD.'
    ],
    perks: ['L&T Build India Scholarship track', 'On-site accommodation & site allowance', 'Structured career path to Project Manager']
  },
  {
    id: 'opp-7',
    title: 'BIM & Digital Twin Modeler Intern',
    company: 'Bentley Systems India',
    companyLogo: '🏢',
    location: 'Pune, Maharashtra (Hybrid)',
    type: 'Internship',
    stipend: '₹40,000 / month',
    duration: '6 Months',
    deadline: '2026-10-22',
    domain: 'Building Information Modeling (BIM) & GIS',
    engineeringCluster: 'Civil & Smart Infrastructure',
    cadToolsRequired: ['Bentley MicroStation', 'Autodesk Revit', 'OpenBridge Modeler', 'QGIS'],
    industryStandards: ['ISO 19650 (BIM Framework)', 'AASHTO'],
    requiredSkills: ['Revit BIM Modeling', 'Structural Analysis (STAAD.Pro)', 'Surveying & GIS', 'AutoCAD Civil 3D'],
    minimumCGPA: 7.8,
    eligibleBranches: ['Civil Engineering', 'Geoinformatics', 'Urban Planning'],
    description: 'Build parametric Level-of-Detail (LOD 350) 3D BIM models and digital twin infrastructure assets for major highway and bridge projects.',
    responsibilities: [
      'Create 3D structural models of bridges and culverts using Bentley OpenBridge and Revit.',
      'Run clash detection between civil utilities, structural elements, and MEP conduits.',
      'Integrate GIS geospatial elevation data into corridor alignments.',
      'Generate 4D construction schedule simulations and quantity take-offs.'
    ],
    perks: ['Bentley Accredited BIM Professional Certificate', 'PPO track for Software Consultant', 'Flexible hybrid work schedule']
  },

  // ─── 4. Electrical, Power Systems & Renewable Energy ───
  {
    id: 'opp-8',
    title: 'Microgrid & Smart Substation Automation Trainee',
    company: 'Schneider Electric India',
    companyLogo: '🔌',
    location: 'Bengaluru / Hyderabad (Onsite)',
    type: 'Full-time',
    stipend: '₹8.2 LPA',
    duration: 'Full-time Role',
    deadline: '2026-11-05',
    domain: 'Power Systems & Substation Automation',
    engineeringCluster: 'Electrical, Power Systems & Renewable Energy',
    cadToolsRequired: ['ETAP', 'MATLAB Simulink (SimPowerSystems)', 'EcoStruxure'],
    industryStandards: ['IEC 61850', 'IEEE 1547 (Interconnection)', 'IEC 60870-5-104'],
    requiredSkills: ['MATLAB / Simulink', 'Power Electronics', 'PLC & SCADA Automation', 'Power Systems Analysis', 'Circuit Analysis & SPICE'],
    minimumCGPA: 7.6,
    eligibleBranches: ['Electrical Engineering', 'Electrical & Electronics Engineering (EEE)', 'Power Systems'],
    description: 'Design protection coordination schemes, solar microgrid controllers, and IEC 61850 substation automation architecture.',
    responsibilities: [
      'Simulate load flow, short circuit, and motor starting dynamics in ETAP and Simulink.',
      'Configure GOOSE messaging and MMS protocols on Schneider digital protection relays.',
      'Develop human-machine interface (HMI) and PLC logic for islanded microgrid transitions.',
      'Participate in factory acceptance testing (FAT) with state power utility engineers.'
    ],
    perks: ['₹8.2 LPA + bonus', 'Global Schneider University training credits', 'Rotation through R&D and field commissioning']
  },
  {
    id: 'opp-9',
    title: 'EV Inverter & Motor Control R&D Intern',
    company: 'Siemens Energy / Siemens Digital Industries',
    companyLogo: '⚙️',
    location: 'Kalwa / Bengaluru (Onsite)',
    type: 'Internship',
    stipend: '₹42,000 / month',
    duration: '6 Months',
    deadline: '2026-10-28',
    domain: 'Power Electronics & Motor Drives',
    engineeringCluster: 'Electrical, Power Systems & Renewable Energy',
    cadToolsRequired: ['MATLAB / Simulink', 'PLECS', 'Altium Designer'],
    industryStandards: ['ISO 26262', 'IEC 61800-5-1'],
    requiredSkills: ['Power Electronics', 'Motor Drives & FOC', 'Battery Management (BMS)', 'MATLAB / Simulink', 'Embedded C'],
    minimumCGPA: 8.0,
    eligibleBranches: ['Electrical Engineering', 'Power Electronics', 'Electronics & Electrical (EEE)'],
    description: 'Implement Field-Oriented Control (FOC) algorithms and space vector PWM (SVPWM) on SiC (Silicon Carbide) 800V EV traction inverters.',
    responsibilities: [
      'Model PMSM motor electromagnetic dynamics in MATLAB/Simulink and PLECS.',
      'Write embedded C code for DSP / microcontroller PWM generation and sensorless observer.',
      'Test inverter efficiency and thermal limits on high-voltage dyno test bench.',
      'Analyze switching losses and gate driver protection under short circuit conditions.'
    ],
    perks: ['Siemens Power Electronics Certification', 'PPO pipeline', 'Direct exposure to 800V silicon carbide test benches']
  },

  // ─── 5. Computer Science & AI / IT ───
  {
    id: 'opp-10',
    title: 'ML Research Intern — Remote Sensing & Earth Observation',
    company: 'ISRO Space Applications Centre (SAC)',
    companyLogo: '🛰️',
    location: 'Ahmedabad, Gujarat (Onsite)',
    type: 'Internship',
    stipend: '₹40,000 / month',
    duration: '6 Months',
    deadline: '2026-10-20',
    domain: 'Machine Learning / Remote Sensing',
    engineeringCluster: 'Computer Science & Information Technology',
    cadToolsRequired: ['PyTorch', 'QGIS', 'CUDA'],
    industryStandards: ['OGC Standards', 'IEEE TGRS'],
    requiredSkills: ['Python', 'TensorFlow / PyTorch', 'Machine Learning', 'Pandas & NumPy', 'Git & Linux'],
    minimumCGPA: 8.0,
    eligibleBranches: ['Computer Science and Engineering', 'AI & Data Science', 'Information Technology'],
    description: 'Work alongside ISRO scientists developing deep learning vision models for crop yield forecasting and satellite image classification using Cartosat and LISS-IV multispectral data.',
    responsibilities: [
      'Train CNN and Vision Transformer models on ISRO multispectral datasets.',
      'Implement reproducible ML pipelines with MLflow and DVC.',
      'Publish or co-author a technical paper in an IEEE journal.',
      'Present weekly findings to SAC Remote Sensing Division.'
    ],
    perks: ['Government Research Fellowship Certificate', 'Co-authorship on ISRO technical report', 'Letter of Recommendation from SAC Scientist']
  },
  {
    id: 'opp-11',
    title: 'Distributed Systems Engineer — Core Infrastructure',
    company: 'Razorpay Systems Engineering',
    companyLogo: '💳',
    location: 'Bengaluru, Karnataka (Hybrid)',
    type: 'Full-time',
    stipend: '₹18.5 LPA',
    duration: 'Full-time Role',
    deadline: '2026-11-15',
    domain: 'Distributed Systems & Fintech Infrastructure',
    engineeringCluster: 'Computer Science & Information Technology',
    cadToolsRequired: ['Docker', 'Kubernetes', 'Prometheus', 'Grafana'],
    industryStandards: ['PCI-DSS Level 1', 'gRPC / Protocol Buffers'],
    requiredSkills: ['Distributed Systems', 'C++', 'Python', 'SQL & Data Pipelines', 'Git & Linux'],
    minimumCGPA: 7.8,
    eligibleBranches: ['Computer Science and Engineering', 'Information Technology', 'Software Engineering'],
    description: 'Design and build sub-millisecond payment settlement engines running on Raft consensus protocols, handling over 250 million daily transactions.',
    responsibilities: [
      'Implement high-throughput distributed state machine replication using Raft.',
      'Optimize TCP and gRPC network serialization overhead for microservices.',
      'Architect horizontal sharding and failover strategies across multiple cloud regions.',
      'Ensure 99.999% payment transaction uptime under flash sale loads.'
    ],
    perks: ['₹18.5 LPA base + equity stock options', 'MacBook Pro M3 Max workstation', '₹1.5 Lakh home office & learning allowance']
  }
];
